package com.example.android.justjava;


import android.content.Intent;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
import java.text.NumberFormat;

/**
 * This app displays an order form to order coffee.
 */
public class MainActivity extends AppCompatActivity {

    int quantity = 0;
    boolean hasWhippedCream = true;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    /**
     * This method is to increment the quantity when the + button is clicked.
     */
    public void increment(View view) {
        if(quantity==100)
            return;
        quantity = quantity + 1;
        display(quantity);
    }
    /**
     * This method is to decrement the quantity when the - button is clicked.
     */
    public void decrement(View view) {
        if(quantity==1)
            return;
        quantity = quantity - 1;
        display(quantity);
    }
    /**
     * This method is called when the order button is clicked.
     */
    public void submitOrder(View view) {
        // For edit text
        EditText text = (EditText)findViewById(R.id.name_field);
        String name = text.getText().toString();

        // for whipped cream
        CheckBox whippedCreamCheckBox = (CheckBox) findViewById(R.id.whipped_cream_checkbox);
        boolean hasWhippedCreamCheckBox = whippedCreamCheckBox.isChecked();

        // for chocolate checkbox
        CheckBox chocolateCheckBox = (CheckBox) findViewById(R.id.chocolate_checkbox);
        boolean haschocolateCheckBox = chocolateCheckBox.isChecked();


        //Log.v("MainActivity", "The price is " + price); // to check which line in the code is having problem
        int price = calculatePrice(hasWhippedCreamCheckBox, haschocolateCheckBox);
        String PriceMessage = createOrderSummary(name,price, hasWhippedCreamCheckBox, haschocolateCheckBox); // also passing the boolean value generated bycheckbox

        Intent intent = new Intent(Intent.ACTION_SENDTO);
        intent.setData(Uri.parse("mailto:")); // only email apps should handle this
        intent.putExtra(Intent.EXTRA_SUBJECT, "Just java order for "+ name);
        intent.putExtra(Intent.EXTRA_TEXT, PriceMessage);
        if (intent.resolveActivity(getPackageManager()) != null) {
            startActivity(intent);
        }
    }
    // to calculate the price
    private int calculatePrice( boolean addWhippedCream, boolean choco) {
        int basePrice=5;
        if(addWhippedCream)
            basePrice += 1;
        if(choco)
            basePrice += 2;
        return quantity * basePrice;
    }

    // it will set the summary message
    private String createOrderSummary(String name, int price, boolean addWhippedCream, boolean choco) {
        String priceMessage;
        priceMessage = "Name: "+ name;
        priceMessage += "\nAdd whipped cream? "+ addWhippedCream;
        priceMessage += "\nAdd Chocolate? "+ choco;
        priceMessage += "\nQuantity: "+ quantity;
        priceMessage += "\nTotal: $" + price;
        priceMessage += "\nThank you!";
        return priceMessage;
    }

    /**
     * This method displays the given quantity value on the screen.
     */
    private void display(int number) {
        TextView quantityTextView = (TextView) findViewById( R.id.quantity_text_view);
        quantityTextView.setText("" + number);
    }

    /**
     * This method displays the given price on the screen.
     */
//    private void displayPrice(int number) {
//        TextView priceTextView = (TextView) findViewById(R.id.order_summary_text_view);
//        priceTextView.setText(NumberFormat.getCurrencyInstance().format(number));
//    }


    /**
     * This method displays the given text on the screen.
     */
    private void displayQuantity(int numberOfCoffees) {
        TextView quantityTextView = (TextView) findViewById(R.id.quantity_text_view);
        quantityTextView.setText("" + numberOfCoffees);
    }


    /* handling checkbox
    public void onCheckboxClicked(View view) {
        hasWhippedCream = ((CheckBox) view).isChecked();

        //String a ;
        //if(hasWhippedCream){
            //str = createOrderSummary(price);
            //a = "Add whipped cream? True \n" ;
          //  return hasWhippedCream;
        //}
        //else{
            //str = createOrderSummary(price);
            // a = "Add whipped cream? False \n"  ;
          //  return hasWhippedCream;
        //}
        //displayMessage(a);
        //return a;
    }
    */





}